name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: angelocp-01/logistics-infrastructure/.github/workflows/node-service.yml@main
    with:
      service-name: gateway
      push-image: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    secrets: inherit
